### ISSUE TITLE
Bibliography not being generated in alphabetical order

### ISSUE THREAD

**Issue by pereirajulioc** [thiagodp/abnt-no-word#3]
I am using the plug in in Word on a MacAir. References are being generated correctly, however when I add the complete bibliography, it does come in alphabetical order. BTW, great work! Thanks!

**Comment by thiagodp** [comment]
Hello, @pereirajulioc . Are you using the non-numerical style?

![image](https://github.com/user-attachments/assets/4d9580c0-5f71-4e71-adc4-f29eab37d60f)

**Comment by thiagodp** [comment]
Hi Julio, 

there may be a problem with Word for MacOS. My results on Windows:

![image](https://github.com/user-attachments/assets/a63c9a27-8493-4257-9f3d-9eea33b5c403)

**Comment by thiagodp** [comment]
I found a thread about this [here](https://discussions.apple.com/thread/252319767?sortBy=rank). 
As a workaround, some people are [converting the Bibliography to static text and then applying AZ sort](https://answers.microsoft.com/en-us/msoffice/forum/all/apa-bibliography-not-sorted-alphabetically-for/803b684c-4f45-4b5c-82ec-8199cebe3bd9).

**Comment by pereirajulioc** [comment]
Thiago,

I suspected it was a bug with Word for Mac… thanks for the prompt replay.

Cheers,

Julio Pereira | +55(11)961896370 | ***@***.***
